"""Deleted strCatDescription

Revision ID: 2abc3a4b2154
Revises: a5a28a9b1779
Create Date: 2023-10-15 11:30:26.709637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abc3a4b2154'
down_revision = 'a5a28a9b1779'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('produce_admin_fkey', 'produce', type_='foreignkey')
    op.drop_column('produce', 'admin')
    op.drop_column('produce', 'strCatDescription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce', sa.Column('strCatDescription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('produce', sa.Column('admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('produce_admin_fkey', 'produce', 'admins', ['admin'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
