"""Deleted contact column in produce

Revision ID: 40d948f5ef99
Revises: 71ed28c261d3
Create Date: 2023-10-15 05:15:48.326589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d948f5ef99'
down_revision = '71ed28c261d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produce', 'strContact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce', sa.Column('strContact', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
