"""Created relationships in database

Revision ID: 71ed28c261d3
Revises: c1490e4d34a9
Create Date: 2023-10-15 05:12:26.828365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ed28c261d3'
down_revision = 'c1490e4d34a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['id'])
    op.add_column('produce', sa.Column('admin', sa.Integer(), nullable=True))
    op.drop_constraint('produce_strCatDescription_fkey', 'produce', type_='foreignkey')
    op.create_foreign_key(None, 'produce', 'admins', ['admin'], ['id'], ondelete='CASCADE')
    op.drop_column('produce', 'strCatDescription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce', sa.Column('strCatDescription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'produce', type_='foreignkey')
    op.create_foreign_key('produce_strCatDescription_fkey', 'produce', 'categories', ['strCatDescription'], ['strCatDescription'], ondelete='CASCADE')
    op.drop_column('produce', 'admin')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
