"""strCatDescription has been reprogrammed to be automatically filled once the strCategory is provided test 2 

Revision ID: 82ce479d1f43
Revises: ec2d45ff4925
Create Date: 2023-10-15 05:31:47.413269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ce479d1f43'
down_revision = 'ec2d45ff4925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produce', 'strCatDescription',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produce', 'strCatDescription',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
