"""strCatDescription has been reprogrammed to be automatically filled once the strCategory is provided test 3 

Revision ID: a5a28a9b1779
Revises: 82ce479d1f43
Create Date: 2023-10-15 05:40:27.429521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a28a9b1779'
down_revision = '82ce479d1f43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
