"""strCatDescription has been reprogrammed to be automatically filled once the strCategory is provided 

Revision ID: ec2d45ff4925
Revises: 40d948f5ef99
Create Date: 2023-10-15 05:29:08.313196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2d45ff4925'
down_revision = '40d948f5ef99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce', sa.Column('strCatDescription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produce', 'strCatDescription')
    # ### end Alembic commands ###
